### ISSUE TITLE
How do I join the server?

### ISSUE THREAD

**Issue by akhilesh-k** [kaustubhai/discord-bot#1]

**Comment by kaustubhai** [comment]
The work on the bot is currently under work. Once it gets finishes I'll
update the readme. Star the repo to stay connected aur baaki whatsapp kr
lia kro😂😂😂
Regards:  Kaustubh Mishra
<https://in.linkedin.com/in/kaustubhai?trk=profile-badge>

**Comment by akhilesh-k** [comment]
Wow, my issue resolved so quickly. Chomu 😂
